gocardless/bump

- Gemfile
- Gemfile.lock
Bumps [webmock](https://github.com/bblimke/webmock) to 1.22.2
- [Changelog](https://github.com/bblimke/webmock/blob/master/CHANGELOG.md)
- [Commits](https://github.com/bblimke/webmock/commits)
> Bump webmock to 1.22.2

- Gemfile
- Gemfile.lock
Bumps [shoryuken](https://github.com/phstc/shoryuken) to 2.0.2
- [Changelog](https://github.com/phstc/shoryuken/blob/master/CHANGELOG.md)
- [Commits](https://github.com/phstc/shoryuken/commits)
> Bump shoryuken to 2.0.2

- Gemfile
- Gemfile.lock
Bumps [aws-sdk](https://github.com/aws/aws-sdk-ruby) to 2.1.33
- [Changelog](https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md)
- [Commits](https://github.com/aws/aws-sdk-ruby/commits)
> Bump aws-sdk to 2.1.33

- app/dependency.rb
Thoughtbot do this. No downside to supporting.
> Support calling your changelog "news"

- app/workers/dependency_file_fetcher.rb
- app/workers/dependency_file_parser.rb
- app/workers/update_checker.rb
- spec/app/workers/dependency_file_parser_spec.rb
- spec/app/workers/update_checker_spec.rb
Currently, if `Workers::DependencyFileFetcher`, `Workers::DependencyFileParser` or ``Workers::UpdateChecker` fail then they will attempt to retry themselves immediately, and indefinitely.
> Better error handling

- Gemfile
- Gemfile.lock
Bumps [sentry-raven](https://github.com/getsentry/raven-ruby) to 0.15.5.
- [Changelog](https://github.com/getsentry/raven-ruby/blob/master/changelog.md)
- [Commits](https://github.com/getsentry/raven-ruby/commits)
> Bump sentry-raven to 0.15.5

- Gemfile
- Gemfile.lock
Bumps [webmock](https://github.com/bblimke/webmock) to 1.24.0.
- [Changelog](https://github.com/bblimke/webmock/blob/master/CHANGELOG.md)
- [Commits](https://github.com/bblimke/webmock/commits)
> Bump webmock to 1.24.0

- app/dependency_file_updaters/ruby.rb
Pretty sure this isn't doing anything. Looks like a mistake in https://github.com/gocardless/bump/commit/1798bc7e25f18f5f9bd49b78f0dc1869ecf04561.
> Remove unnecessary temporary directory use

- app/dependency.rb
Here's an example of such a changelog: https://github.com/twilio/twilio-ruby/blob/master/CHANGES.md
See https://github.com/gocardless/bump/issues/105
> Dependency: Support calling your changlog CHANGES

- .travis.yml
- Gemfile
- Gemfile.lock
- Rakefile
- use the default Rake task to run CI
- update Rubygems and Bundler in CI
- adds rake to Gemfile, changes bundler ver to latest
> Use the default rake task on Travis to run CI

- README.md
This trivial change - use SVG instead of PNG - makes the README look shinier on Github.
> README: Use SVG for Deploy to Heroku btn

- .travis.yml
- app/dependency.rb
- app/pull_request_creator.rb
- app/workers/dependency_file_updater.rb
- app/workers/pull_request_creator.rb
- app/workers/update_checker.rb
- spec/app/dependency_spec.rb
- spec/app/pull_request_creator_spec.rb
- spec/app/workers/dependency_file_updater_spec.rb
- spec/app/workers/pull_request_creator_spec.rb
- spec/app/workers/update_checker_spec.rb
- spec/fixtures/github/business_tags.json
Most open source projects follow the convention of tagging their releases, as `v{version}` (e.g. `v1.4.0`). We can take advantage of this to generate comparison URLs, which show us more accurately the changes between two versions.
If we have tags for the old and new version:
https://github.com/org/repo/compare/v0.1.0...v0.2.0
If we don't have a tag/knowledge of the previous version, we can still show just the commits in this release:
https://github.com/org/repo/commits/v0.2.0
If we don't have any tags, we can fallback to the old URL and just show /commits
https://github.com/org/repo/commits
> Generate a compare(old, new) URL for PRs

- app/update_checkers/node.rb
- spec/app/dependency_file_updaters/ruby_spec.rb
- spec/app/update_checkers/node_spec.rb
See https://docs.npmjs.com/misc/scope
The package "@gocardless/stubby" is an example of this.
http://registry.npmjs.org/@gocardless/stubby is a 404, but http://registry.npmjs.org/@gocardless%2Fstubby is 👌
> Handle scoped npm package names

- .gitignore
- Rakefile
- app/dependency.rb
- app/dependency_file_parsers/ruby.rb
- app/dependency_source_code_finders/node.rb
- app/dependency_source_code_finders/ruby.rb
- app/update_checkers/base.rb
- app/update_checkers/node.rb
- app/update_checkers/ruby.rb
- app/workers/dependency_file_fetcher.rb
- spec/app/workers/dependency_file_fetcher_spec.rb
- spec/app/workers/dependency_updater_spec.rb
Looks like Bump has stopped providing detailed context in PRs.
I think this is because `language` is no longer being set on an individual `Dependency` object, and therefore we never try to contact Github to resolve more details about the change: https://github.com/gocardless/bump/blob/23b63f996308f8eb4d50d2b3b3e64f3fa4b01d2b/app/dependency.rb#L23
* Use the new `Dependency#to_h` method when serializing/deserializing these instances. This might lead to passing around `nil` keys (we could consider compacting the hash), but at least it's explicit about our apis are.
* Repo has `#language` also. We could probably avoid duplication, and not also apply language to the `Dependency` object. @hmac thoughts?
> Fix pull request messages

- app/dependency_source_code_finders/node.rb
- app/dependency_source_code_finders/python.rb
- app/update_checkers/node.rb
- app/update_checkers/python.rb
- spec/app/dependency_source_code_finders/python_spec.rb
Fixes https://exceptions.gocardless.com/gocardless/bump/issues/7723
> Use open-uri for HTTP requests, so we follow redirects

- app/dependency_file_updaters/node.rb
- spec/app/dependency_file_updaters/node_spec.rb
We don't want to hear about Yarn's progress - no-one's watching STDOUT when it runs anyway.
Returns specs to being an uninterrupted sea of green.
> Don't output to STDOUT when performing node bumps

- app/dependency.rb
- app/dependency_source_code_finders/base.rb
- spec/app/dependency_source_code_finders/ruby_spec.rb
- spec/fixtures/rubygems_response_period_github.yaml
Github allows full stops in repo names. For example, see https://github.com/octokit/octokit.rb
Also removes some unused constants.
> Don't strip full stops from Github link URLs

- spec/fixtures/gemfiles/comments
- spec/lib/dependency_file_updaters/ruby_spec.rb
Ensures we're not accidentally nuking comments from Gemfiles.
> Add spec for preserving Gemfile comments

- .gitignore
- Gemfile
- Gemfile.lock
- bump.gemspec
The Gemfile now only contains dependencies necessary for running the self-hosted version of bump.
> Add a gemspec, and move core dependencies there

- lib/bump/update_checkers/base.rb
- lib/bump/update_checkers/ruby.rb
- spec/lib/update_checkers/ruby_spec.rb
Not all files in the Gemfile will appear in the Gemfile.lock. For instance, if a gem specifies `platform: [:windows]`, and the Gemfile.lock is generated on a Linux machine, the gem will be not appear
in the lockfile.
Previously we would blow up in this case, now we just skip over the gem.
> Skip gems that aren't in the lockfile

- lib/bump/dependency_file_updaters/ruby.rb
Cleans up use of `$&`, and makes updating the Gemfile.lock more robust (and closer to being able to handle gems with multiple requirements, which is coming soon).
> Clearer Ruby gemfile updating code

- Gemfile.lock
- bump.gemspec
Heroku only permits specific bundler versions that work with their
environment, so we can't be too picky about the version we want.
> Allow any Bundler version >= 1.12.0

- Gemfile
- Gemfile.lock
This fixes an issue where we're not following pypi redirects for some python packages.
> Bump bump-core to 0.1.1

- Gemfile
- Gemfile.lock
- app/workers/dependency_file_fetcher.rb
- app/workers/dependency_updater.rb
- bin/bump_dependencies_for_repo
- spec/app/workers/dependency_file_fetcher_spec.rb
- spec/app/workers/dependency_updater_spec.rb
`bump-core` v0.3.3 introduced some JavaScript bug fixes it would be a shame for GoCardless not to be taking advantage of. In particularly, you probably haven't been seeing changelogs for any of your JavaScript dependency bumps when you should have been.
This PR moves `bump` to use the latest version of `bump-core`. Once merged, you should also update any scheduled jobs on Heroku to use `javascript` as the language, rather than `node`.
✌️
> Use latest version of bump-core

- Gemfile
- Gemfile.lock
No reason for you guys not to be on the latest bump-core. Only breaking change in there was to make `language` required for `Bump::Dependency`, but you don't create those manually anywhere anyway.
https://github.com/gocardless/bump-core/blob/master/CHANGELOG.md
> Use bump-core 0.4.1

- README.md
The current readme is out of date - it should point anyone who wants to contribute to `bump-core` instead.
> Update readme to point to bump-core

- Gemfile
- Gemfile.lock
- app/workers/dependency_updater.rb
- spec/app/workers/dependency_file_fetcher_spec.rb
- spec/app/workers/dependency_updater_spec.rb
This fixes [the weird issue](https://github.com/gocardless/bump-core/issues/34) where bump bumps some random gem but not the one on the PR title.
Specs look good, but I'd like to test this out on staging first.
> Bump bump-core to v0.5.0

- Gemfile
- Gemfile.lock
`v0.5.1` introduced a new format for branch names, so any existing branches will need to be closed otherwise we'll get some dupes.
> Update bump-core to v0.5.5

- README.md
We're now using [dependabot](http://www.dependabot.com) to keep our dependencies up to date, that means we're effectively deprecating the use of bump.
I don't think we should alter the README as I believe this is still relevant in the case where you'd like to host your own internal version of a dependency checker.
> Update the README.md to reflect deprecation

- app/boot.rb
In `app/boot.rb`, we try to set Bundler's settings to "unfreeze" the bundle for the purposes of our tests. This has been broken for a little while due to a changed API in Bundler since v1.16.0,
resulting in [errors when running the tests][circle-gocardless-bump-258]:
```
An error occurred while loading ./spec/app/workers/dependency_file_fetcher_spec.rb.
Failure/Error: Bundler.settings[:frozen] = "0"
NoMethodError:
undefined method `[]=' for #<Bundler::Settings:0x00000002958f38>
Did you mean?  []
```
Bundler removed this API for tweaking the settings in [June][8ccf49c], but an alternative means for updating them was introduced before that in [August 2016][3b6dd37].
This switches to using the way that is in Bundler now: using `Bundler::Settings#temporary`.
[circle-gocardless-bump-258]: …
> Fix the specs by manipulating Bundler's settings differently
